site_name: PFE 25.2 8002 II
site_url: https://projetos-de-extensao.github.io/PFE_25.2_8002_II/

theme:
  name: material
  language: pt-BR
repo_url: https://github.com/Projetos-de-Extensao/PFE_25.2_8002_II
repo_name: GitHub
nav:
  - Início: index.md
  - Design Thinking:
      - 5W2H: design-thinking/5w2h.md
      - Brainstorm: design-thinking/Brainstorm.md
      - Histórias de Usuário: design-thinking/historiasdeusuario.md
      - Mapas Mentais: design-thinking/mapa_mental.md
      - Pesquisa de Mercado: design-thinking/pesquisa.md
      - Protótipo Baixa Fidelidade: design-thinking/prototipo_baixa_fidelidade.md
  - Sprint Planning:
      - Sprint Planning: sprint-planning/sprint.md
  - Repositório: https://github.com/Projetos-de-Extensao/PFE_25.2_8002_II

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

